services:
  - type: web
    name: physicslab
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 300
    envVars:
      - key: PORT
        value: 10000
    plan: free
